/** @format */

"use client";
import { Josefin_Sans } from "next/font/google";
import Footer from "@/components/ui/footer";
import { LayoutProvider } from "@/contexts/layout-context";
import Link from "next/link";

import "./globals.css";
export const metadata = {
  title: "Indigo Consulting App",
  description: "Generated by create next app",
};

const inter = Josefin_Sans({
  weight: ["100", "200", "300", "400"],
  subsets: ["latin"],
});

export default function GlobalError({ error, reset }) {
  return (
    // global-error must include html and body tags
    <html lang="en" className={inter.className}>
      <body>
        <div className="properties-loading-layout">
          {/* <Header className="non-hero"></Header> */}
          <main>
            <h2>Global Error - something went wrong!</h2>
            <button onClick={() => reset()}>Try again</button>
            <div>
              <Link href="/">Return to homepage</Link>
            </div>
          </main>
        </div>
        {/* <Footer></Footer> */}
      </body>
    </html>
  );
}
