/** @format */
import { Lato } from "next/font/google";
import { SessionProvider } from "@/contexts/session-context";
import { LayoutProvider } from "@/contexts/layout-context";
import { Providers } from "./providers.jsx";

import "./globals.css";
// import { validateRequest } from "@/auth/lucia";
export const metadata = {
  title: {
    template: "Indigo Consulting %s",
    default: "Indigo Consulting",
  },
  keywords: [
    "Greece",
    "Development",
    "Consulting",
    "Luxury",
    "Redevelopment",
    "Golden visa",
    "Market Analysis",
  ],
  description: "Generated by create next app",
  authors: [{ name: "Adam" }, { name: "Kasia" }],
  creator: "Kasia Kruk",
  publisher: "Kasia Kruk",
};
const inter = Lato({
  weight: ["100", "300", "400"],
  subsets: ["latin"],
});

export default async function RootLayout({ children }) {
  // const session = await validateRequest();
  return (
    <html lang="en" className={inter.className}>
      <body>
        <LayoutProvider>
          {/* <SessionProvider value={session}> */}
          <Providers>{children}</Providers>
          {/* </SessionProvider> */}
        </LayoutProvider>
      </body>
    </html>
  );
}
