/** @format */
import { Josefin_Sans } from "next/font/google";
import { SessionProvider } from "@/contexts/session-context";
import { LayoutProvider } from "@/contexts/layout-context";
import { Providers } from "./providers.jsx";

import "./globals.css";
import { validateRequest } from "@/auth/lucia";
export const metadata = {
  title: "Indigo Consulting App",
  description: "Generated by create next app",
};
const inter = Josefin_Sans({
  weight: ["100", "200", "300", "400"],
  subsets: ["latin"],
});

export default async function RootLayout({ children }) {
  const session = await validateRequest();
  return (
    <html lang="en" className={inter.className}>
      <body>
        <LayoutProvider>
          <SessionProvider value={session}>
            <Providers>{children}</Providers>
          </SessionProvider>
        </LayoutProvider>
      </body>
    </html>
  );
}
