/** @format */
import { Antic_Didone } from 'next/font/google'
import { SessionProvider } from "@/contexts/session-context";
import { LayoutProvider } from "@/contexts/layout-context";

import "./globals.css";
import { validateRequest } from "@/lib/auth";
export const metadata = {
  title: "Indigo Consulting App",
  description: "Generated by create next app",
};

const inter = Antic_Didone({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export default async function RootLayout({ children }) {
  const session = await validateRequest();
  return (
    <html lang="en" className={inter.className}>
      <body>
        <LayoutProvider>
          <SessionProvider value={session}>{children}</SessionProvider>
        </LayoutProvider>
      </body>
    </html>
  );
}
