/** @format */

import Header from "@/components/ui/header/header";
import Footer from "@/components/ui/footer";
import { Josefin_Sans } from "next/font/google";
import Link from "next/link";
import HeroComponent from "@/components/hero/hero-component";
import classes from "./page.module.css"
import heroImage from "/public/images/croppednight.jpg";

import "./globals.css";
export const metadata = {
  title: "Indigo Consulting App",
  description: "Generated by create next app",
};

const inter = Josefin_Sans({
  weight: ["100", "200", "300", "400"],
  subsets: ["latin"],
});

export default function NotFound() {
  return (
    <>
      <div className={classes.pageWrapper}>
        <HeroComponent heroImage={heroImage} altText="Alt text" header footer>
          <div className={classes.formcontainer}>
          <h1>Page not found!</h1>
        <div>
          <Link href="/">Return to homepage</Link>
        </div>
          </div>
        </HeroComponent>
      </div>

      {/* <Header></Header>
      <main className="not-found">
        <h1>Page not found!</h1>
        <div>
          <Link href="/">Return to homepage</Link>
        </div>
      </main> */}

    </>
  );
}
