/** @format */

import { Lato } from "next/font/google";
import Link from "next/link";
import HeroComponent from "@/components/hero/hero-component";
import classes from "./page.module.css";
import heroImage from "/public/images/croppednight.jpg";

import "./globals.css";
export const metadata = {
  title: "Indigo Consulting App",
  description: "Generated by create next app",
};

const inter = Lato({
  weight: ["100", "300", "400"],
  subsets: ["latin"],
});

export default function NotFound() {
  return (
    <>
      <div className={classes.pageWrapper}>
        <HeroComponent heroImage={heroImage} altText="Alt text" header footer>
          <div className={classes.formcontainer}>
            <h1>Page not found!</h1>
            <div>
              <Link href="/">Return to homepage</Link>
            </div>
          </div>
        </HeroComponent>
      </div>
    </>
  );
}
